server:
  port: 9090

spring:
  application:
    name: IDENTITY-SERVICE
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 1 day
    refresh-token:
      expiration: 604800000 # 7 days

  customCipherConfig:
    encoder:
      secret: 01$3456789A4C71#
      iv: 01$3456789A4C71#

logging:
  level:
    root: INFO
    com.tanveer.auth-service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%M - %msg%n"
