version: '3.9'

services:
  # ========================
  # Infrastructure
  # ========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ========================
  # Databases
  # ========================
  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth-service
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-product:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product-service
    ports:
      - "5434:5432"
    volumes:
      - postgres_product_data:/var/lib/postgresql/data

  postgres-inventory:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: inventory-service
    ports:
      - "5435:5432"
    volumes:
      - postgres_inventory_data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order-service
    ports:
      - "5436:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  postgres-agent:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: agent
    ports:
      - "5437:5432"
    volumes:
      - postgres_agent_data:/var/lib/postgresql/data

  # ========================
  # Common Library Build
  # ========================
  common-lib:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: common-lib
    working_dir: /app
    volumes:
      - ./common-lib:/app
      - maven-repo:/root/.m2
    command: mvn clean install -DskipTests

  # ========================
  # Microservices
  # ========================
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"

  cloud-config-server:
    build: ./cloud-config-server
    ports:
      - "8888:8888"
    depends_on:
      - service-registry

  api-gateway:
    build: ./api-gateway
    ports:
      - "8989:8989"
    depends_on:
      - service-registry
      - cloud-config-server

  auth-service:
    build: ./auth-service
    ports:
      - "9090:9090"
    depends_on:
      - postgres-auth
      - kafka
      - service-registry
      - cloud-config-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/auth-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "9091:9091"
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - postgres-product
      - kafka
      - service-registry
      - cloud-config-server
      - common-lib
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/product-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  inventory-service:
    build:
      context: .
      dockerfile: ./inventory-service/Dockerfile
    depends_on:
      - kafka
      - service-registry
      - cloud-config-server
      - postgres-inventory
      - common-lib
    volumes:
      - maven-repo:/root/.m2
    ports:
      - "9093:9093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/inventory-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
    ports:
      - "9094:9094"
    volumes:
      - maven-repo:/root/.m2
    depends_on:
      - postgres-order
      - kafka
      - service-registry
      - cloud-config-server
      - common-lib
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/order-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  agent:
    build: ./agent
    ports:
      - "9095:9095"
    depends_on:
      - postgres-agent
      - kafka
      - service-registry
      - cloud-config-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/agent
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  postgres_auth_data:
  postgres_product_data:
  postgres_inventory_data:
  postgres_order_data:
  postgres_agent_data:
  maven-repo: