spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment/**
              filters:
                - name: Authentication
                - name: CircuitBreaker
                  args:
                    name: paymentCircuitBreaker
                    fallbackUri: forward:/paymentFallBack

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: Authentication
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/orderFallBack

            - id: identity-service
              uri: lb://IDENTITY-SERVICE
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: Authentication
                - name: CircuitBreaker
                  args:
                    name: identityCircuitBreaker
                    fallbackUri: forward:/identityFallBack

            - id: product-service
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/v1/products/**
              filters:
                - name: Authentication
                - name: CircuitBreaker
                  args:
                    name: productCircuitBreaker
                    fallbackUri: forward:/productFallBack

            - id: product-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/inventories/**
              filters:
                - name: Authentication
                - name: CircuitBreaker
                  args:
                    name: productCircuitBreaker
                    fallbackUri: forward:/inventoryFallBack

server:
  port: 8989

auth:
  service:
    url: http://IDENTITY-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, health, info

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        registerHealthIndicator: true
    instances:
      paymentCircuitBreaker:
        baseConfig: default
      orderCircuitBreaker:
        baseConfig: default
      identityCircuitBreaker:
        baseConfig: default
      productCircuitBreaker:
        baseConfig: default
      inventoryCircuitBreaker:
        baseConfig: default


logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}.%M - %msg%n"