application:
  services:
    inventory:
      url: ${INVENTORY_SERVICE_URL:http://localhost:9093/api/v1/inventories}
server:
  port: 9094

spring:
  application:
    name: order-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://cloud-config-server:8888}"
